/*  id, name, img, about, group  */

export const storeProducts = [

  {
    id: 2,
    name: "SERIJA LINE",
    img: "./images/20.jpg",
    img2: "./images/21.jpg",
    img3: "./images/22.jpg",
    img4: "./images/23.jpg",
    img5: "./images/24.jpg",
    img6: "./images/25.jpg",
    b1: "./images/bedz/16.png",
    b2: "./images/bedz/18.png",
    b3: "./images/bedz/led.png",
    b4: "./images/bedz/okov.png",
    b5: "./images/bedz/gloss.png",
    about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
    group: "Lorem "
  },
  {
    id: 5,
    name: "SERIJA KARAMEL",
    img: "./images/50.jpg",
    img2: "./images/51.jpg",
    img3: "./images/52.jpg",
    img4: "./images/53.jpg",
    img5: "./images/54.jpg",
    img6: "./images/55.jpg",
    b1: "./images/bedz/16.png",
    b2: "./images/bedz/18.png",
    b3: "./images/bedz/led.png",
    b4: "./images/bedz/okov.png",
    b5: "./images/bedz/gloss.png",
    b6: "./images/bedz/karamel.png",
    about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
    group: "Lorem "
  },
  {
    id: 6,
    name: "SERIJA FIT",
    img: "./images/60.jpg",
    img2: "./images/61.jpg",
    img3: "./images/62.jpg",
    img4: "./images/63.jpg",
    b1: "./images/bedz/16.png",
    b2: "./images/bedz/18.png",
    b3: "./images/bedz/led.png",
    b4: "./images/bedz/okov.png",
    b5: "./images/bedz/gloss.png",
    about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
    group: "Lorem "
  },
  {
    id: 7,
    name: "serija tulip",
    img: "./images/7.jpg",
    img2: "./images/7.jpg",
    b1: "./images/bedz/16.png",
    b2: "./images/bedz/18.png",
    b3: "./images/bedz/led.png",
    b4: "./images/bedz/okov.png",
    b5: "./images/bedz/gloss.png",
    about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
    group: "Lorem "
  },
  {
    id: 8,
    name: "SERIJA LIGHT",
    img: "./images/80.jpg",
    img2: "./images/81.jpg",
    img3: "./images/82.jpg",
    img4: "./images/83.jpg",
    img5: "./images/84.jpg",
    img6: "./images/85.jpg",
    b1: "./images/bedz/16.png",
    b2: "./images/bedz/18.png",
    b3: "./images/bedz/led.png",
    b4: "./images/bedz/okov.png",
    b5: "./images/bedz/gloss.png",
    b6: "./images/bedz/light.png",
    about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
    group: "Light",
    vName: "VERTIKALA LIGHT SA KORPOM KONZOLNA",
    vSifra: "35-880",
    vDimenzije: "350x300x1520",
    ogName: "OGLEDALO LIGHT",
    ogSifra1: "35-875",
    ogDimenzije1: "510x250x700",
    ogSifra2: "35-876",
    ogDimenzije2: "610x250x700",
    ogSifra3: "35-877",
    ogDimenzije3: "710x250x700",
    ormName: "ORMARIC LIGHT KONZOLNI",
    ormSifra1: "35-870",
    ormDimenzije1: "510x460x500",
    ormSifra2: "35-871",
    ormDimenzije2: "610x460x500",
    ormSifra3: "35-872",
    ormDimenzije3: "710x460x500",


  },
  {
    id: 9,
    name: "Vertikale",
    img: "./images/90.jpg",
    img2: "./images/91.jpg",
    img3: "./images/92.jpg",
    img4: "./images/93.jpg",
    img5: "./images/94.jpg",
    img6: "./images/95.jpg",
    img7: "./images/96.jpg",
    img8: "./images/97.jpg",
    b1: "./images/bedz/16.png",
    b2: "./images/bedz/18.png",
    b3: "./images/bedz/led.png",
    b4: "./images/bedz/okov.png",
    b5: "./images/bedz/gloss.png",
    about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
    group: "Lorem "
  },
  {
    id: 10,
    name: "Serija Sonoma",
    img: "./images/10.jpg",
    img2: "./images/11.jpg",
    img3: "./images/12.jpg",
    img4: "./images/13.jpg",
    img5: "./images/14.jpg",
    img6: "./images/15.jpg",
    b1: "./images/bedz/16.png",
    b2: "./images/bedz/18.png",
    b3: "./images/bedz/led.png",
    b4: "./images/bedz/okov.png",
    b5: "./images/bedz/gloss.png",
    b6: "./images/bedz/sonoma.png",
    about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
    group: "Lorem "
  },
  {
    id: 11,
    name: "SERIJA SLIM",
    img: "./images/100.jpg",
    img2: "./images/101.jpg",
    img3: "./images/102.jpg",
    img4: "./images/103.jpg",
    img5: "./images/104.jpg",
    img6: "./images/105.jpg",
    img7: "./images/106.jpg",
    img8: "./images/107.jpg",
    img9: "./images/108.jpg",
    img10: "./images/109.jpg",
    img11: "./images/110.jpg",
    b1: "./images/bedz/16.png",
    b2: "./images/bedz/18.png",
    b3: "./images/bedz/led.png",
    b4: "./images/bedz/okov.png",
    b5: "./images/bedz/gloss.png",
    about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
    group: "Lorem "
  },
  {
    id: 12,
    name: "SERIJA KARAMEL LIGHT WHITE",
    img: "./images/120.jpg",
    img2: "./images/121.jpg",
    img3: "./images/122.jpg",
    img4: "./images/123.jpg",
    img5: "./images/124.jpg",
    img6: "./images/125.jpg",
    img7: "./images/126.jpg",
    img8: "./images/127.jpg",
    b1: "./images/bedz/16.png",
    b2: "./images/bedz/18.png",
    b3: "./images/bedz/led.png",
    b4: "./images/bedz/okov.png",
    b5: "./images/bedz/gloss.png",
    about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
    group: "Lorem "
  }
]

export const detailProduct = {
  id: 111,
  name: "detaljji",
  img: "./images/10.jpg",
  about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
  group: "Lorem "
};

// id, name,img,about,group,inCart,count,total