/*  id, name, img, about, group  */

export const storeProducts = [

  {
    id: 1,
    name: "SERIJA LINE",
    img: "./images/JPEG/20.jpg",
    img2: "./images/21.jpg",
    img3: "./images/22.jpg",
    img4: "./images/23.jpg",
    img5: "./images/24.jpg",
    img6: "./images/25.jpg",
    b1: "./images/bedz/16.png",
    b2: "./images/bedz/18.png",
    b3: "./images/bedz/led.png",
    b4: "./images/bedz/okov.png",
    b5: "./images/bedz/gloss.png",
    about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
    group: "Lorem "
  },
  {
    id: 2,
    name: "SERIJA KARAMEL",
    img: "./images/JPEG/50.jpg",
    img2: "./images/51.jpg",
    img3: "./images/52.jpg",
    img4: "./images/53.jpg",
    img5: "./images/54.jpg",
    img6: "./images/55.jpg",
    b1: "./images/bedz/16.png",
    b2: "./images/bedz/18.png",
    b3: "./images/bedz/led.png",
    b4: "./images/bedz/okov.png",
    b5: "./images/bedz/gloss.png",
    b6: "./images/bedz/karamel.png",
    about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
    group: "Lorem "
  },
  {
    id: 3,
    name: "SERIJA LIGHT",
    img: "./images/JPEG/80.jpg",
    img2: "./images/81.jpg",
    img3: "./images/82.jpg",
    img4: "./images/83.jpg",
    img5: "./images/84.jpg",
    img6: "./images/85.jpg",
    b1: "./images/bedz/16.png",
    b2: "./images/bedz/18.png",
    b3: "./images/bedz/led.png",
    b4: "./images/bedz/okov.png",
    b5: "./images/bedz/gloss.png",
    b6: "./images/bedz/light.png",
    about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
    group: "Light",
    vName: "VERTIKALA LIGHT SA KORPOM KONZOLNA",
    vSifra: "35-880",
    vDimenzije: "350x300x1520",
    ogName: "OGLEDALO LIGHT",
    ogSifra1: "35-875",
    ogDimenzije1: "510x250x700",
    ogSifra2: "35-876",
    ogDimenzije2: "610x250x700",
    ogSifra3: "35-877",
    ogDimenzije3: "710x250x700",
    ormName: "ORMARIC LIGHT KONZOLNI",
    ormSifra1: "35-870",
    ormDimenzije1: "510x460x500",
    ormSifra2: "35-871",
    ormDimenzije2: "610x460x500",
    ormSifra3: "35-872",
    ormDimenzije3: "710x460x500",


  },
  {
    id: 4,
    name: "Serija Sonoma",
    img: "./images/JPEG/10.jpg",
    img2: "./images/11.jpg",
    img3: "./images/12.jpg",
    img4: "./images/13.jpg",
    img5: "./images/14.jpg",
    img6: "./images/15.jpg",
    b1: "./images/bedz/16.png",
    b2: "./images/bedz/18.png",
    b3: "./images/bedz/led.png",
    b4: "./images/bedz/okov.png",
    b5: "./images/bedz/gloss.png",
    b6: "./images/bedz/sonoma.png",
    about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
    group: "Lorem "
  },
  // ************************ ORMARICI ***********************
  {
    id: 5,
    name: "ORMARIC FIT KONZOLNI",
    img: "./images/JPEG/61.jpg",
    img2: "./images/61.jpg",
    img3: "./images/62.jpg",
    // img4: "./images/63.jpg",
    b1: "./images/bedz/16.png",
    b2: "./images/bedz/18.png",
    b3: "./images/bedz/led.png",
    b4: "./images/bedz/okov.png",
    b5: "./images/bedz/gloss.png",
    about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
    group: "ormarici",
    ormName: "ORMARIC KONZOLNI FIT + LAVABO SLIM",
    ormSifra1: "35-350",
    ormDimenzije1: "500x400x500",
    ormSifra2: "35-351",
    ormDimenzije2: "600x400x500",
    ormSifra3: "35-352",
    ormDimenzije3: "700x400x500",
  },
  {
    id: 6,
    name: "ORMARIC LUX KONZOLNI",
    img: "./images/JPEG/130.jpg",
    img2: "./images/130.jpg",
    img3: "./images/130.jpg",
    // img4: "./images/63.jpg",
    b1: "./images/bedz/16.png",
    b2: "./images/bedz/18.png",
    b3: "./images/bedz/led.png",
    b4: "./images/bedz/okov.png",
    b5: "./images/bedz/gloss.png",
    about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
    group: "ormarici",
    ormName: "ORMARIC KONZOLNI LUX + LAVABO SLIM",
    ormSifra1: "35-920",
    ormDimenzije1: "550x340x500",
    ormSifra2: "35-670",
    ormDimenzije2: "510x460x500",
    ormSifra3: "35-671",
    ormDimenzije3: "610x460x500",
    ormSifra4: "35-672",
    ormDimenzije4: "710x460x500",
  },
  {
    id: 7,
    name: "ORMARIC LUX",
    img: "./images/JPEG/135.jpg",
    img2: "./images/135.jpg",
    img3: "./images/135.jpg",
    // img4: "./images/63.jpg",
    b1: "./images/bedz/16.png",
    b2: "./images/bedz/18.png",
    b3: "./images/bedz/led.png",
    b4: "./images/bedz/okov.png",
    b5: "./images/bedz/gloss.png",
    about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
    group: "ormarici",
    ormName: "ORMARIC LUX + LAVABO SLIM",
    ormSifra1: "35-750",
    ormDimenzije1: "510x460x850",
    ormSifra2: "35-751",
    ormDimenzije2: "610x460x850",
    ormSifra3: "35-752",
    ormDimenzije3: "710x460x850",
  },
  {
    id: 8,
    name: "ORMARIC LUX 810",
    img: "./images/JPEG/810.jpg",
    img2: "./images/810.jpg",
    img3: "./images/810.jpg",
    // img4: "./images/63.jpg",
    b1: "./images/bedz/16.png",
    b2: "./images/bedz/18.png",
    b3: "./images/bedz/led.png",
    b4: "./images/bedz/okov.png",
    b5: "./images/bedz/gloss.png",
    about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
    group: "ormarici",
    ormName: "ORMARIC LUX + LAVABO SLIM",
    ormSifra1: "35-753",
    ormDimenzije1: "810x460x850",
    // ormSifra2: "35-751",
    // ormDimenzije2: "610x460x850",
    // ormSifra3: "35-752",
    // ormDimenzije3: "710x460x850",
  },
  {
    id: 9,
    name: "ORMARIC LUX 910",
    img: "./images/JPEG/910.jpg",
    img2: "./images/910.jpg",
    img3: "./images/910.jpg",
    // img4: "./images/63.jpg",
    b1: "./images/bedz/16.png",
    b2: "./images/bedz/18.png",
    b3: "./images/bedz/led.png",
    b4: "./images/bedz/okov.png",
    b5: "./images/bedz/gloss.png",
    about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
    group: "ormarici",
    ormName: "ORMARIC LUX + LAVABO SLIM",
    ormSifra1: "35-754",
    ormDimenzije1: "910x460x850",
    ormSifra2: "35-755",
    ormDimenzije2: "1010x460x850",
    // ormSifra3: "35-752",
    // ormDimenzije3: "710x460x850",
  },
  {
    id: 10,
    name: "ORMARIC SLIM",
    img: "./images/JPEG/101.jpg",
    img2: "./images/101.jpg",
    img3: "./images/101.jpg",
    // img4: "./images/63.jpg",
    b1: "./images/bedz/16.png",
    b2: "./images/bedz/18.png",
    b3: "./images/bedz/led.png",
    b4: "./images/bedz/okov.png",
    b5: "./images/bedz/gloss.png",
    about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
    group: "ormarici",
    ormName: "ORMARIC SLIM + LAVABO SLIM",
    ormSifra1: "35-200",
    ormDimenzije1: "410x460x850",
    ormSifra2: "35-201",
    ormDimenzije2: "510x460x850",
    ormSifra3: "35-202",
    ormDimenzije3: "610x460x850",
    ormSifra4: "35-203",
    ormDimenzije4: "710x460x850",
  },
  {
    id: 20,
    name: "ORMARIC WHITE KONZOLNI",
    img: "./images/JPEG/126.jpg",
    img2: "./images/126.jpg",
    img3: "./images/126.jpg",
    // img4: "./images/63.jpg",
    b1: "./images/bedz/16.png",
    b2: "./images/bedz/18.png",
    b3: "./images/bedz/led.png",
    b4: "./images/bedz/okov.png",
    b5: "./images/bedz/gloss.png",
    about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
    group: "ormarici",
    ormName: "ORMARIC KONZOLNI WHITE + LAVABO ALVIT",
    ormSifra1: "35-198",
    ormDimenzije1: "450x250x500",
    // ormSifra2: "35-351",
    // ormDimenzije2: "600x400x500",
    // ormSifra3: "35-352",
    // ormDimenzije3: "700x400x500",
  },
  {
    id: 21,
    name: "ORMARIC KARAMEL KONZOLNI",
    img: "./images/JPEG/124.jpg",
    img2: "./images/124.jpg",
    img3: "./images/124.jpg",
    // img4: "./images/63.jpg",
    b1: "./images/bedz/16.png",
    b2: "./images/bedz/18.png",
    b3: "./images/bedz/led.png",
    b4: "./images/bedz/okov.png",
    b5: "./images/bedz/gloss.png",
    about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
    group: "ormarici",
    ormName: "ORMARIC KONZOLNI KARAMEL + LAVABO ALVIT",
    ormSifra1: "35-195",
    ormDimenzije1: "450x250x500",
  },
  {
    id: 22,
    name: "ORMARIC KONZOLNI 500 ART - A1",
    img: "./images/JPEG/A1.jpg",
    img2: "./images/A1.jpg",
    img3: "./images/A1.jpg",
    // img4: "./images/63.jpg",
    b1: "./images/bedz/16.png",
    b2: "./images/bedz/18.png",
    b3: "./images/bedz/led.png",
    b4: "./images/bedz/okov.png",
    b5: "./images/bedz/gloss.png",
    about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
    group: "ormarici",
    ormName: "ORMARIC KONZOLNI 500 ART-A1",
    ormSifra1: "35-800-A1",
    ormDimenzije1: "500x500x500",
  },
  {
    id: 23,
    name: "ORMARIC KONZOLNI 500 ART - A2",
    img: "./images/JPEG/A2.jpg",
    img2: "./images/A2.jpg",
    img3: "./images/A2.jpg",
    // img4: "./images/63.jpg",
    b1: "./images/bedz/16.png",
    b2: "./images/bedz/18.png",
    b3: "./images/bedz/led.png",
    b4: "./images/bedz/okov.png",
    b5: "./images/bedz/gloss.png",
    about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
    group: "ormarici",
    ormName: "ORMARIC KONZOLNI 500 ART-A2",
    ormSifra1: "35-800-A",
    ormDimenzije1: "500x500x500",
  },
  {
    id: 24,
    name: "ORMARIC KONZOLNI 500 ART - A3",
    img: "./images/JPEG/A3.jpg",
    img2: "./images/A3.jpg",
    img3: "./images/A3.jpg",
    // img4: "./images/63.jpg",
    b1: "./images/bedz/16.png",
    b2: "./images/bedz/18.png",
    b3: "./images/bedz/led.png",
    b4: "./images/bedz/okov.png",
    b5: "./images/bedz/gloss.png",
    about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
    group: "ormarici",
    ormName: "ORMARIC KONZOLNI 500 ART-A3",
    ormSifra1: "35-800-A3",
    ormDimenzije1: "500x500x500",
  },
  {
    id: 25,
    name: "ORMARIC KONZOLNI 500 ART - A4",
    img: "./images/JPEG/A4.jpg",
    img2: "./images/A4.jpg",
    img3: "./images/A4.jpg",
    // img4: "./images/63.jpg",
    b1: "./images/bedz/16.png",
    b2: "./images/bedz/18.png",
    b3: "./images/bedz/led.png",
    b4: "./images/bedz/okov.png",
    b5: "./images/bedz/gloss.png",
    about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
    group: "ormarici",
    ormName: "ORMARIC KONZOLNI 500 ART-A4",
    ormSifra1: "35-800-A4",
    ormDimenzije1: "500x500x500",
  },
  {
    id: 26,
    name: "ORMARIC KONZOLNI 500 ART - A5",
    img: "./images/JPEG/A5.jpg",
    img2: "./images/A5.jpg",
    img3: "./images/A5.jpg",
    // img4: "./images/63.jpg",
    b1: "./images/bedz/16.png",
    b2: "./images/bedz/18.png",
    b3: "./images/bedz/led.png",
    b4: "./images/bedz/okov.png",
    b5: "./images/bedz/gloss.png",
    about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
    group: "ormarici",
    ormName: "ORMARIC KONZOLNI 500 ART-A5",
    ormSifra1: "35-800-A5",
    ormDimenzije1: "500x500x500",
  },
  {
    id: 27,
    name: "ORMARIC LUX + LAVABO TULIP",
    img: "./images/JPEG/140.jpg",
    img2: "./images/140.jpg",
    img3: "./images/140.jpg",
    // img4: "./images/63.jpg",
    b1: "./images/bedz/16.png",
    b2: "./images/bedz/18.png",
    b3: "./images/bedz/led.png",
    b4: "./images/bedz/okov.png",
    b5: "./images/bedz/gloss.png",
    about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
    group: "ormarici",
    ormName: "ORMARIC LUX + LAVABO TULIP",
    ormSifra1: "35-151",
    ormDimenzije1: "550x460x850",
    ormSifra2: "35-152",
    ormDimenzije2: "650x460x850",
  },
  {
    id: 28,
    name: "ORMARIC LUX + LAVABO TULIP 800",
    img: "./images/JPEG/141.jpg",
    img2: "./images/141.jpg",
    img3: "./images/141.jpg",
    // img4: "./images/63.jpg",
    b1: "./images/bedz/16.png",
    b2: "./images/bedz/18.png",
    b3: "./images/bedz/led.png",
    b4: "./images/bedz/okov.png",
    b5: "./images/bedz/gloss.png",
    about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
    group: "ormarici",
    ormName: "ORMARIC LUX + LAVABO TULIP",
    ormSifra1: "35-153",
    ormDimenzije1: "800x460x850",
    // ormSifra2: "35-152",
    // ormDimenzije2: "650x460x850",
  },
  {
    id: 29,
    name: "ORMARIC + LAVABO TULIP",
    img: "./images/JPEG/142.jpg",
    img2: "./images/142.jpg",
    img3: "./images/142.jpg",
    // img4: "./images/63.jpg",
    b1: "./images/bedz/16.png",
    b2: "./images/bedz/18.png",
    b3: "./images/bedz/led.png",
    b4: "./images/bedz/okov.png",
    b5: "./images/bedz/gloss.png",
    about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
    group: "ormarici",
    ormName: "ORMARIC + LAVABO TULIP",
    ormSifra1: "35-402",
    ormDimenzije1: "550x460x850",
    ormSifra2: "35-403",
    ormDimenzije2: "650x460x850",
  },
  {
    id: 30,
    name: "ORMARIC + LAVABO TULIP 800",
    img: "./images/JPEG/143.jpg",
    img2: "./images/143.jpg",
    img3: "./images/143.jpg",
    // img4: "./images/63.jpg",
    b1: "./images/bedz/16.png",
    b2: "./images/bedz/18.png",
    b3: "./images/bedz/led.png",
    b4: "./images/bedz/okov.png",
    b5: "./images/bedz/gloss.png",
    about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
    group: "ormarici",
    ormName: "ORMARIC + LAVABO TULIP 800",
    ormSifra1: "35-404",
    ormDimenzije1: "800x460x850",
    ormSifra2: "35-405",
    ormDimenzije2: "1000x460x850",
  },
  {
    id: 31,
    name: "ORMARIC FIOKA + LAVABO TULIP",
    img: "./images/JPEG/144.jpg",
    img2: "./images/144.jpg",
    img3: "./images/144.jpg",
    // img4: "./images/63.jpg",
    b1: "./images/bedz/16.png",
    b2: "./images/bedz/18.png",
    b3: "./images/bedz/led.png",
    b4: "./images/bedz/okov.png",
    b5: "./images/bedz/gloss.png",
    about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
    group: "ormarici",
    ormName: "ORMARIC FIOKA + LAVABO TULIP",
    ormSifra1: "35-406",
    ormDimenzije1: "550x460x850",
    ormSifra2: "35-407",
    ormDimenzije2: "650x460x850",
  },
  {
    id: 32,
    name: "ORMARIC FIOKA + LAVABO TULIP 800",
    img: "./images/JPEG/145.jpg",
    img2: "./images/145.jpg",
    img3: "./images/145.jpg",
    // img4: "./images/63.jpg",
    b1: "./images/bedz/16.png",
    b2: "./images/bedz/18.png",
    b3: "./images/bedz/led.png",
    b4: "./images/bedz/okov.png",
    b5: "./images/bedz/gloss.png",
    about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
    group: "ormarici",
    ormName: "ORMARIC FIOKA + LAVABO TULIP 800",
    ormSifra1: "35-408",
    ormDimenzije1: "800x460x850",
    ormSifra2: "35-409",
    ormDimenzije2: "1000x460x850",
  },
  {
    id: 33,
    name: "ORMARIC + LAVABO SLIM 1200",
    img: "./images/JPEG/150.jpg",
    img2: "./images/150.jpg",
    img3: "./images/150.jpg",
    // img4: "./images/63.jpg",
    b1: "./images/bedz/16.png",
    b2: "./images/bedz/18.png",
    b3: "./images/bedz/led.png",
    b4: "./images/bedz/okov.png",
    b5: "./images/bedz/gloss.png",
    about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
    group: "ormarici",
    ormName: "ORMARIC + LAVABO SLIM 1200",
    ormSifra1: "35-207",
    ormDimenzije1: "1200x460x850",
    // ormSifra2: "35-409",
    // ormDimenzije2: "1000x460x850",
  },
  // ****************** END ORMARICI *************************
  // ****************** OGLEDALA *****************************
  {
    id: 100,
    name: "OGLEDALO KARAMEL",
    img: "./images/ogledala/JPEG/121.jpg",
    img2: "./images/ogledala/121.jpg",
    img3: "./images/ogledala/121.jpg",
    // img4: "./images/63.jpg",
    b1: "./images/bedz/16.png",
    b2: "./images/bedz/18.png",
    b3: "./images/bedz/led.png",
    b4: "./images/bedz/okov.png",
    b5: "./images/bedz/gloss.png",
    about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
    group: "ogledala",
    ormName: "OGLEDALO KARAMEL",
    ormSifra1: "35-190",
    ormDimenzije1: "450x120x600",
  },
  {
    id: 101,
    name: "OGLEDALO LIGHT",
    img: "./images/ogledala/JPEG/123.jpg",
    img2: "./images/ogledala/123.jpg",
    img3: "./images/ogledala/123.jpg",
    // img4: "./images/63.jpg",
    b1: "./images/bedz/16.png",
    b2: "./images/bedz/18.png",
    b3: "./images/bedz/led.png",
    b4: "./images/bedz/okov.png",
    b5: "./images/bedz/gloss.png",
    about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
    group: "ogledala",
    ormName: "OGLEDALO LIGHT",
    ormSifra1: "35-191",
    ormDimenzije1: "450x120x600",
  },
  {
    id: 102,
    name: "OGLEDALO SLIM - LUX",
    img: "./images/ogledala/JPEG/127.jpg",
    img2: "./images/ogledala/127.jpg",
    img3: "./images/ogledala/127.jpg",
    b1: "./images/bedz/16.png",
    b2: "./images/bedz/18.png",
    b3: "./images/bedz/led.png",
    b4: "./images/bedz/okov.png",
    b5: "./images/bedz/gloss.png",
    about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
    group: "ogledala",
    ormName: "OGLEDALO SLIM - LUX",
    ormSifra1: "35-700",
    ormDimenzije1: "510x280x750",
    ormSifra2: "35-701",
    ormDimenzije2: "610x280x750",
  },
  {
    id: 103,
    name: "OGLEDALO SLIM - LUX 800",
    img: "./images/ogledala/JPEG/125.jpg",
    img2: "./images/ogledala/125.jpg",
    img3: "./images/ogledala/125.jpg",
    b1: "./images/bedz/16.png",
    b2: "./images/bedz/18.png",
    b3: "./images/bedz/led.png",
    b4: "./images/bedz/okov.png",
    b5: "./images/bedz/gloss.png",
    about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
    group: "ogledala",
    ormName: "OGLEDALO SLIM - LUX",
    ormSifra1: "35-702",
    ormDimenzije1: "710x280x750",
    ormSifra2: "35-703",
    ormDimenzije2: "810x280x750",
  },
  {
    id: 104,
    name: "OGLEDALO TEA 800",
    img: "./images/ogledala/JPEG/126.jpg",
    img2: "./images/ogledala/126.jpg",
    img3: "./images/ogledala/126.jpg",
    b1: "./images/bedz/16.png",
    b2: "./images/bedz/18.png",
    b3: "./images/bedz/led.png",
    b4: "./images/bedz/okov.png",
    b5: "./images/bedz/gloss.png",
    about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
    group: "ogledala",
    ormName: "OGLEDALO TEA 800",
    ormSifra1: "35-653",
    ormDimenzije1: "810x250x710",
    ormSifra2: "35-654",
    ormDimenzije2: "910x280x750",
    ormSifra2: "35-655",
    ormDimenzije2: "1010x280x750",
  },
  {
    id: 105,
    name: "OGLEDALO SLIM",
    img: "./images/ogledala/JPEG/124.jpg",
    img2: "./images/ogledala/124.jpg",
    img3: "./images/ogledala/124.jpg",
    b1: "./images/bedz/16.png",
    b2: "./images/bedz/18.png",
    b3: "./images/bedz/led.png",
    b4: "./images/bedz/okov.png",
    b5: "./images/bedz/gloss.png",
    about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
    group: "ogledala",
    ormName: "OGLEDALO SLIM",
    ormSifra1: "35-231",
    ormDimenzije1: "510x250x750",
    ormSifra2: "35-232",
    ormDimenzije2: "610x280x750",
  },
  {
    id: 106,
    name: "OGLEDALO TEA",
    img: "./images/ogledala/JPEG/128.jpg",
    img2: "./images/ogledala/128.jpg",
    img3: "./images/ogledala/128.jpg",
    b1: "./images/bedz/16.png",
    b2: "./images/bedz/18.png",
    b3: "./images/bedz/led.png",
    b4: "./images/bedz/okov.png",
    b5: "./images/bedz/gloss.png",
    about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
    group: "ogledala",
    ormName: "OGLEDALO TEA",
    ormSifra1: "35-650",
    ormDimenzije1: "510x250x710",
    ormSifra2: "35-651",
    ormDimenzije2: "610x250x710",
    ormSifra3: "35-652",
    ormDimenzije3: "710x250x710",
  },
  {
    id: 107,
    name: "OGLEDALO TULIP - LUX",
    img: "./images/ogledala/JPEG/ogl tulip lux 550.jpg",
    img2: "./images/ogledala/ogl tulip lux 550.jpg",
    img3: "./images/ogledala/ogl tulip lux 550.jpg",
    b1: "./images/bedz/16.png",
    b2: "./images/bedz/18.png",
    b3: "./images/bedz/led.png",
    b4: "./images/bedz/okov.png",
    b5: "./images/bedz/gloss.png",
    about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
    group: "ogledala",
    ormName: "OGLEDALO TULIP - LUX",
    ormSifra1: "35-650",
    ormDimenzije1: "550x230x700",
    // ormSifra2: "35-651",
    // ormDimenzije2: "610x250x710",
    // ormSifra3: "35-652",
    // ormDimenzije3: "710x250x710",
  },
  {
    id: 108,
    name: "OGLEDALO TULIP - LUX 800",
    img: "./images/ogledala/JPEG/orm tulip lux 650 800.jpg",
    img2: "./images/ogledala/orm tulip lux 650 800.jpg",
    img3: "./images/ogledala/orm tulip lux 650 800.jpg",
    b1: "./images/bedz/16.png",
    b2: "./images/bedz/18.png",
    b3: "./images/bedz/led.png",
    b4: "./images/bedz/okov.png",
    b5: "./images/bedz/gloss.png",
    about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
    group: "ogledala",
    ormName: "OGLEDALO TULIP - LUX 800",
    ormSifra1: "35-182",
    ormDimenzije1: "650x230x700",
    ormSifra2: "35-183",
    ormDimenzije2: "800x250x710",
    // ormSifra3: "35-652",
    // ormDimenzije3: "710x250x710",
  },
  {
    id: 109,
    name: "OGLEDALO EKO",
    img: "./images/ogledala/JPEG/ogl eko 550 650.jpg",
    img2: "./images/ogledala/ogl eko 550 650.jpg",
    img3: "./images/ogledala/ogl eko 550 650.jpg",
    b1: "./images/bedz/16.png",
    b2: "./images/bedz/18.png",
    b3: "./images/bedz/led.png",
    b4: "./images/bedz/okov.png",
    b5: "./images/bedz/gloss.png",
    about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
    group: "ogledala",
    ormName: "OGLEDALO EKO",
    ormSifra1: "35-061",
    ormDimenzije1: "550x180x610",
    ormSifra2: "35-062",
    ormDimenzije2: "650x180x610",
    // ormSifra3: "35-652",
    // ormDimenzije3: "710x250x710",
  },
  {
    id: 110,
    name: "OGLEDALO EKO 800",
    img: "./images/ogledala/JPEG/ogl eko 800 1000.jpg",
    img2: "./images/ogledala/ogl eko 800 1000.jpg",
    img3: "./images/ogledala/ogl eko 800 1000.jpg",
    b1: "./images/bedz/16.png",
    b2: "./images/bedz/18.png",
    b3: "./images/bedz/led.png",
    b4: "./images/bedz/okov.png",
    b5: "./images/bedz/gloss.png",
    about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
    group: "ogledala",
    ormName: "OGLEDALO EKO 800",
    ormSifra1: "35-063",
    ormDimenzije1: "800x180x640",
    ormSifra2: "35-064",
    ormDimenzije2: "1000x180x640",
    // ormSifra3: "35-652",
    // ormDimenzije3: "710x250x710",
  },
  {
    id: 111,
    name: "OGLEDALO TULIP",
    img: "./images/ogledala/JPEG/ogl gornji deo tulip 550 650.jpg",
    img2: "./images/ogledala/ogl gornji deo tulip 550 650.jpg",
    img3: "./images/ogledala/ogl gornji deo tulip 550 650.jpg",
    b1: "./images/bedz/16.png",
    b2: "./images/bedz/18.png",
    b3: "./images/bedz/led.png",
    b4: "./images/bedz/okov.png",
    b5: "./images/bedz/gloss.png",
    about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
    group: "ogledala",
    ormName: "OGLEDALO TULIP",
    ormSifra1: "35-030",
    ormDimenzije1: "550x180x1000",
    ormSifra2: "35-031",
    ormDimenzije2: "650x180x1000",
    // ormSifra3: "35-652",
    // ormDimenzije3: "710x250x710",
  },
  {
    id: 112,
    name: "OGLEDALO TULIP 800",
    img: "./images/ogledala/JPEG/ogl  eko 800 1000  d.jpg",
    img2: "./images/ogledala/ogl  eko 800 1000  d.jpg",
    img3: "./images/ogledala/ogl  eko 800 1000  d.jpg",
    b1: "./images/bedz/16.png",
    b2: "./images/bedz/18.png",
    b3: "./images/bedz/led.png",
    b4: "./images/bedz/okov.png",
    b5: "./images/bedz/gloss.png",
    about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
    group: "ogledala",
    ormName: "OGLEDALO TULIP 800",
    ormSifra1: "35-032",
    ormDimenzije1: "800x180x1000",
    ormSifra2: "35-033",
    ormDimenzije2: "1000x180x1000",
    // ormSifra3: "35-652",
    // ormDimenzije3: "710x250x710",
  },
  {
    id: 113,
    name: "OGLEDALO TEA 1200",
    img: "./images/ogledala/JPEG/ogl tea 1200.jpg",
    img2: "./images/ogledala/ogl tea 1200.jpg",
    img3: "./images/ogledala/ogl tea 1200.jpg",
    b1: "./images/bedz/16.png",
    b2: "./images/bedz/18.png",
    b3: "./images/bedz/led.png",
    b4: "./images/bedz/okov.png",
    b5: "./images/bedz/gloss.png",
    about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
    group: "ogledala",
    ormName: "OGLEDALO TEA 1200",
    ormSifra1: "35-656",
    ormDimenzije1: "1200x130x700",
    // ormSifra2: "35-033",
    // ormDimenzije2: "1000x180x1000",
    // ormSifra3: "35-652",
    // ormDimenzije3: "710x250x710",
  },
  {
    id: 114,
    name: "OGLEDALO X-02",
    img: "./images/ogledala/JPEG/ogl x02.jpg",
    img2: "./images/ogledala/ogl x02.jpg",
    img3: "./images/ogledala/ogl x02.jpg",
    b1: "./images/bedz/16.png",
    b2: "./images/bedz/18.png",
    b3: "./images/bedz/led.png",
    b4: "./images/bedz/okov.png",
    b5: "./images/bedz/gloss.png",
    about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
    group: "ogledala",
    ormName: "OGLEDALO X-02",
    ormSifra1: "35-104",
    ormDimenzije1: "460x230x640",
  },
  {
    id: 115,
    name: "OGLEDALO X-03",
    img: "./images/ogledala/JPEG/ogl x03.jpg",
    img2: "./images/ogledala/ogl x03.jpg",
    img3: "./images/ogledala/ogl x03.jpg",
    b1: "./images/bedz/16.png",
    b2: "./images/bedz/18.png",
    b3: "./images/bedz/led.png",
    b4: "./images/bedz/okov.png",
    b5: "./images/bedz/gloss.png",
    about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
    group: "ogledala",
    ormName: "OGLEDALO X-03",
    ormSifra1: "35-103",
    ormDimenzije1: "610x230x640",
  },
  {
    id: 116,
    name: "OGLEDALO EKO-03",
    img: "./images/ogledala/JPEG/ogl eko 03.jpg",
    img2: "./images/ogledala/ogl eko 03.jpg",
    img3: "./images/ogledala/ogl eko 03.jpg",
    b1: "./images/bedz/16.png",
    b2: "./images/bedz/18.png",
    b3: "./images/bedz/led.png",
    b4: "./images/bedz/okov.png",
    b5: "./images/bedz/gloss.png",
    about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
    group: "ogledala",
    ormName: "OGLEDALO EKO-03",
    ormSifra1: "35-105",
    ormDimenzije1: "610x130x640",
  },
  {
    id: 117,
    name: "OGLEDALO VIP",
    img: "./images/ogledala/JPEG/VIP.jpg",
    img2: "./images/ogledala/VIP.jpg",
    img3: "./images/ogledala/VIP.jpg",
    b1: "./images/bedz/16.png",
    b2: "./images/bedz/18.png",
    b3: "./images/bedz/led.png",
    b4: "./images/bedz/okov.png",
    b5: "./images/bedz/gloss.png",
    about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
    group: "ogledala",
    ormName: "OGLEDALO VIP",
    ormSifra1: "35-900",
    ormDimenzije1: "510x170x800",
    ormSifra2: "35-901",
    ormDimenzije2: "610x170x800",
  },
  {
    id: 118,
    name: "OGLEDALO SLIM LINE",
    img: "./images/ogledala/JPEG/SLIM.jpg",
    img2: "./images/ogledala/SLIM.jpg",
    img3: "./images/ogledala/SLIM.jpg",
    b1: "./images/bedz/16.png",
    b2: "./images/bedz/18.png",
    b3: "./images/bedz/led.png",
    b4: "./images/bedz/okov.png",
    b5: "./images/bedz/gloss.png",
    about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
    group: "ogledala",
    ormName: "OGLEDALO SLIM LINE",
    ormSifra1: "35-893",
    ormDimenzije1: "610x180x1000",
    ormSifra2: "35-894",
    ormDimenzije2: "710x180x1000",
  },

  {
    id: 120,
    name: "OGLEDALO KARAMEL",
    img: "./images/ogledala/JPEG/KARAMEL.jpg",
    img2: "./images/ogledala/KARAMEL.jpg",
    img3: "./images/ogledala/KARAMEL.jpg",
    b1: "./images/bedz/16.png",
    b2: "./images/bedz/18.png",
    b3: "./images/bedz/led.png",
    b4: "./images/bedz/okov.png",
    b5: "./images/bedz/gloss.png",
    about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
    group: "ogledala",
    ormName: "OGLEDALO KARAMEL",
    ormSifra1: "35-855",
    ormDimenzije1: "510x130x700",
    ormSifra2: "35-856",
    ormDimenzije2: "610x130x700",
    ormSifra3: "35-856",
    ormDimenzije3: "710x130x700",
  },
  {
    id: 121,
    name: "OGLEDALO SONOMA",
    img: "./images/ogledala/JPEG/SONOMA.jpg",
    img2: "./images/ogledala/SONOMA.jpg",
    img3: "./images/ogledala/SONOMA.jpg",
    b1: "./images/bedz/16.png",
    b2: "./images/bedz/18.png",
    b3: "./images/bedz/led.png",
    b4: "./images/bedz/okov.png",
    b5: "./images/bedz/gloss.png",
    about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
    group: "ogledala",
    ormName: "OGLEDALO SONOMA",
    ormSifra1: "35-855",
    ormDimenzije1: "450x120x600",
  },
  {
    id: 119,
    name: "OGLEDALO LIGHT",
    img: "./images/ogledala/JPEG/LIGHT.jpg",
    img2: "./images/ogledala/LIGHT.jpg",
    img3: "./images/ogledala/LIGHT.jpg",
    b1: "./images/bedz/16.png",
    b2: "./images/bedz/18.png",
    b3: "./images/bedz/led.png",
    b4: "./images/bedz/okov.png",
    b5: "./images/bedz/gloss.png",
    about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
    group: "ogledala",
    ormName: "OGLEDALO LIGHT",
    ormSifra1: "35-875",
    ormDimenzije1: "510x130x700",
    ormSifra2: "35-876",
    ormDimenzije2: "610x130x700",
    ormSifra3: "35-877",
    ormDimenzije3: "710x130x700",
  },
  // ****************** END OGLEDALA *************************
  // ****************** VERTIKALE ****************************
  {
    id: 200,
    name: "VERTIKALA MINI BEZ KORPE",
    img: "./images/vertikale/JPEG/mini-bez-korpe.jpg",
    img2: "./images/vertikale/JPEG/mini-bez-korpe.jpg",
    img3: "./images/vertikale/JPEG/mini-bez-korpe.jpg",
    b1: "./images/bedz/16.png",
    b2: "./images/bedz/18.png",
    b3: "./images/bedz/led.png",
    b4: "./images/bedz/okov.png",
    b5: "./images/bedz/gloss.png",
    about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
    group: "vertikale",
    ormName: "VERTIKALA MINI BEZ KORPE",
    ormSifra1: "35-300",
    ormDimenzije1: "350x310x900",
  },
  {
    id: 201,
    name: "VERTIKALA MINI SA KORPOM",
    img: "./images/vertikale/JPEG/mini-sa-korpom.jpg",
    img2: "./images/vertikale/JPEG/mini-sa-korpom.jpg",
    img3: "./images/vertikale/JPEG/mini-sa-korpom.jpg",
    b1: "./images/bedz/16.png",
    b2: "./images/bedz/18.png",
    b3: "./images/bedz/led.png",
    b4: "./images/bedz/okov.png",
    b5: "./images/bedz/gloss.png",
    about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
    group: "vertikale",
    ormName: "VERTIKALA MINI SA KORPOM",
    ormSifra1: "35-301",
    ormDimenzije1: "350x310x900",
  },
  {
    id: 202,
    name: "VERTIKALA 350 SA KORPOM",
    img: "./images/vertikale/JPEG/vertikala(6).jpg",
    img2: "./images/vertikale/JPEG/vertikala(6).jpg",
    img3: "./images/vertikale/JPEG/vertikala(6).jpg",
    b1: "./images/bedz/16.png",
    b2: "./images/bedz/18.png",
    b3: "./images/bedz/led.png",
    b4: "./images/bedz/okov.png",
    b5: "./images/bedz/gloss.png",
    about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
    group: "vertikale",
    ormName: "VERTIKALA 350 SA KORPOM",
    ormSifra2: "35-306",
    ormDimenzije2: "350x300x1900",
  },
  {
    id: 203,
    name: "VERTIKALA 350 BEZ KORPE",
    img: "./images/vertikale/JPEG/vertikala(6).jpg",
    img2: "./images/vertikale/JPEG/vertikala(6).jpg",
    img3: "./images/vertikale/JPEG/vertikala(6).jpg",
    b1: "./images/bedz/16.png",
    b2: "./images/bedz/18.png",
    b3: "./images/bedz/led.png",
    b4: "./images/bedz/okov.png",
    b5: "./images/bedz/gloss.png",
    about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
    group: "vertikale",
    ormName: "VERTIKALA 350 BEZ KORPE",
    ormSifra2: "35-305",
    ormDimenzije2: "350x300x1900",
  },
  {
    id: 212,
    name: "VERTIKALA 500 BEZ KORPE",
    img: "./images/vertikale/JPEG/vertikala-velika(2).jpg",
    img2: "./images/vertikale/JPEG/vertikala-velika(2).jpg",
    img3: "./images/vertikale/JPEG/vertikala-velika(2).jpg",
    b1: "./images/bedz/16.png",
    b2: "./images/bedz/18.png",
    b3: "./images/bedz/led.png",
    b4: "./images/bedz/okov.png",
    b5: "./images/bedz/gloss.png",
    about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
    group: "vertikale",
    ormName: "VERTIKALA 500 BEZ KORPE",
    ormSifra2: "35-308",
    ormDimenzije2: "500x300x1900",
  },
  {
    id: 213,
    name: "VERTIKALA SA KORPOM",
    img: "./images/vertikale/JPEG/vertikala-velika(2).jpg",
    img2: "./images/vertikale/JPEG/vertikala-velika(2).jpg",
    img3: "./images/vertikale/JPEG/vertikala-velika(2).jpg",
    b1: "./images/bedz/16.png",
    b2: "./images/bedz/18.png",
    b3: "./images/bedz/led.png",
    b4: "./images/bedz/okov.png",
    b5: "./images/bedz/gloss.png",
    about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
    group: "vertikale",
    ormName: "VERTIKALA 500 SA KORPOM",
    ormSifra2: "35-307",
    ormDimenzije2: "500x300x1900",
  },
  {
    id: 204,
    name: "VERTIKALA LUX 500 BEZ KORPE",
    img: "./images/vertikale/JPEG/bez-korpe-lux-500.jpg",
    img2: "./images/vertikale/JPEG/bez-korpe-lux-500.jpg",
    img3: "./images/vertikale/JPEG/bez-korpe-lux-500.jpg",
    b1: "./images/bedz/16.png",
    b2: "./images/bedz/18.png",
    b3: "./images/bedz/led.png",
    b4: "./images/bedz/okov.png",
    b5: "./images/bedz/gloss.png",
    about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
    group: "vertikale",
    ormName: "VERTIKALA LUX 500 BEZ KORPE",
    ormSifra2: "35-310",
    ormDimenzije2: "500x300x1900",
  },
  {
    id: 205,
    name: "VERTIKALA 500 LUX SA KORPOM",
    img: "./images/vertikale/JPEG/sa-korpom-lux-500.jpg",
    img2: "./images/vertikale/JPEG/sa-korpom-lux-500.jpg",
    img3: "./images/vertikale/JPEG/sa-korpom-lux-500.jpg",
    b1: "./images/bedz/16.png",
    b2: "./images/bedz/18.png",
    b3: "./images/bedz/led.png",
    b4: "./images/bedz/okov.png",
    b5: "./images/bedz/gloss.png",
    about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
    group: "vertikale",
    ormName: "VERTIKALA 500 LUX SA KORPOM",
    ormSifra2: "35-309",
    ormDimenzije2: "500x300x1900",
  },
  {
    id: 206,
    name: "VERTIKALA 350 LUX BEZ KORPE",
    img: "./images/vertikale/JPEG/sa-korpom-lux-350.jpg",
    img2: "./images/vertikale/JPEG/sa-korpom-lux-350.jpg",
    img3: "./images/vertikale/JPEG/sa-korpom-lux-350.jpg",
    b1: "./images/bedz/16.png",
    b2: "./images/bedz/18.png",
    b3: "./images/bedz/led.png",
    b4: "./images/bedz/okov.png",
    b5: "./images/bedz/gloss.png",
    about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
    group: "vertikale",
    ormName: "VERTIKALA 350 LUX BEZ KORPE",
    ormSifra2: "35-312",
    ormDimenzije2: "350x300x1900",
  },
  {
    id: 207,
    name: "VERTIKALA 350 LUX SA KORPOM",
    img: "./images/vertikale/JPEG/sa-korpom-lux-350.jpg",
    img2: "./images/vertikale/JPEG/sa-korpom-lux-350.jpg",
    img3: "./images/vertikale/JPEG/sa-korpom-lux-350.jpg",
    b1: "./images/bedz/16.png",
    b2: "./images/bedz/18.png",
    b3: "./images/bedz/led.png",
    b4: "./images/bedz/okov.png",
    b5: "./images/bedz/gloss.png",
    about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
    group: "vertikale",
    ormName: "VERTIKALA 350 LUX SA KORPOM",
    ormSifra2: "35-313",
    ormDimenzije2: "350x300x1900",
  },
  {
    id: 208,
    name: "VERTIKALA SONOMA SA KORPOM KONZOLNA",
    img: "./images/vertikale/JPEG/IMG_0665-VERTIKALA-SONOMA.jpg",
    img2: "./images/vertikale/JPEG/IMG_0665-VERTIKALA-SONOMA.jpg",
    img3: "./images/vertikale/JPEG/IMG_0665-VERTIKALA-SONOMA.jpg",
    b1: "./images/bedz/16.png",
    b2: "./images/bedz/18.png",
    b3: "./images/bedz/led.png",
    b4: "./images/bedz/okov.png",
    b5: "./images/bedz/gloss.png",
    about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
    group: "vertikale",
    ormName: "VERTIKALA SONOMA SA KORPOM KONZOLNA",
    ormSifra2: "35-388",
    ormDimenzije2: "350x300x1400",
  },
  {
    id: 209,
    name: "VERTIKALA KARAMEL SA KORPOM KONZOLNA",
    img: "./images/vertikale/JPEG/IMG_0588--VERTIKALA-KARAMEL-KONZOLA.jpg",
    img2: "./images/vertikale/JPEG/IMG_0588--VERTIKALA-KARAMEL-KONZOLA.jpg",
    img3: "./images/vertikale/JPEG/IMG_0588--VERTIKALA-KARAMEL-KONZOLA.jpg",
    b1: "./images/bedz/16.png",
    b2: "./images/bedz/18.png",
    b3: "./images/bedz/led.png",
    b4: "./images/bedz/okov.png",
    b5: "./images/bedz/gloss.png",
    about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
    group: "vertikale",
    ormName: "VERTIKALA KARAMEL SA KORPOM KONZOLNA",
    ormSifra2: "35-860",
    ormDimenzije2: "350x300x1520",
  },
  {
    id: 210,
    name: "VERTIKALA LIGHT SA KORPOM KONZOLNA",
    img: "./images/vertikale/JPEG/IMG_0657-VERTIKALA-LIGHT.jpg",
    img2: "./images/vertikale/JPEG/IMG_0657-VERTIKALA-LIGHT.jpg",
    img3: "./images/vertikale/JPEG/IMG_0657-VERTIKALA-LIGHT.jpg",
    b1: "./images/bedz/16.png",
    b2: "./images/bedz/18.png",
    b3: "./images/bedz/led.png",
    b4: "./images/bedz/okov.png",
    b5: "./images/bedz/gloss.png",
    about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
    group: "vertikale",
    ormName: "VERTIKALA LIGHT SA KORPOM KONZOLNA",
    ormSifra2: "35-880",
    ormDimenzije2: "350x300x1520",
  },
  {
    id: 211,
    name: "VERTIKALA LINE SA KORPOM",
    img: "./images/vertikale/JPEG/IMG_0637-VERTIKALA-LINE(2).jpg",
    img2: "./images/vertikale/JPEG/IMG_0637-VERTIKALA-LINE(2).jpg",
    img3: "./images/vertikale/JPEG/IMG_0637-VERTIKALA-LINE(2).jpg",
    b1: "./images/bedz/16.png",
    b2: "./images/bedz/18.png",
    b3: "./images/bedz/led.png",
    b4: "./images/bedz/okov.png",
    b5: "./images/bedz/gloss.png",
    about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
    group: "vertikale",
    ormName: "VERTIKALA LINE SA KORPOM",
    ormSifra2: "35-896",
    ormDimenzije2: "350x300x900",
  },
  // ****************** END VERTIKALE *************************


]

export const detailProduct = {
  id: 1111,
  name: "detaljji",
  img: "./images/10.jpg",
  about: "Proizvod je izrađen od medijapana debljine 16mm i univera debljine 18mm, bojen poliuretanskim bojama.",
  group: "Lorem "
};


// id, name,img,about,group,inCart,count,total